name: Deploy to GitHub Releases

on:
  push:
    branches:
      - master

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Version from Project File
        id: get-version
        shell: bash
        run: echo "version=$(grep -oE '<Version>[^<]+' ChangeScreenResolution_GUI.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Publish Application
        run: dotnet publish --configuration Release --framework net8.0-windows --runtime win-x64 -o .\publish --self-contained false /p:PublishSingleFile=true

      - name: Install Velopack
        run: dotnet tool install -g vpk

      - name: Download latest release
        run: |
          vpk download github --repoUrl https://github.com/IgnacBrychta/ChangeScreenResolution_GUI
        
      - name: Package Application with Velopack
        run: |
          vpk pack -u ChangeScreenResolution_GUI -p .\publish -e ChangeScreenResolution_GUI.exe -v ${{ steps.get-version.outputs.version }}

      - name: Upload Velopack Release to GitHub
        run: |
          vpk upload github --repoUrl https://github.com/IgnacBrychta/ChangeScreenResolution_GUI --token ${{ secrets.GITHUB_TOKEN }} --publish --releaseName "ChangeScreenResolution_GUI ${{ env.VERSION }}" --tag v${{ env.VERSION }}
