name: Deploy to GitHub Releases

on:
  push:
    branches:
      - master

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get version from project file
        run: |
          version=$(grep -oE '<Version>[^<]+' ChangeScreenResolution_GUI.csproj | sed 's/<Version>//')
          echo "VERSION=${version}" >> $GITHUB_ENV
        shell: bash

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Publish Application
        run: dotnet publish /p:Configuration=Release \
              /p:Platform="Any CPU" \
              /p:PublishDir=.\publish \
              /p:PublishProtocol=FileSystem \
              /p:_TargetId=Folder \
              /p:TargetFramework=net8.0-windows \
              /p:RuntimeIdentifier=win-x64 \
              /p:SelfContained=false \
              /p:PublishSingleFile=true \
              /p:PublishReadyToRun=false

      - name: Install Velopack
        run: dotnet tool install -g vpk

      - name: Download latest release
        run: |
          vpk download github --repoUrl https://github.com/IgnacBrychta/ChangeScreenResolution_GUI
        
      - name: Package Application with Velopack
        run: |
          vpk pack -u MyUniqueIdentifierTest -v "${{ env.VERSION }}" --packDir .\publish --channel win -e ChangeScreenResolution_GUI.exe

      - name: Upload Velopack Release to GitHub
        run: |
          vpk upload github --repoUrl https://github.com/IgnacBrychta/ChangeScreenResolution_GUI --token ${{ secrets.GITHUB_TOKEN }} --publish --releaseName "ChangeScreenResolution_GUI ${{ env.VERSION }}" --tag v${{ env.VERSION }}
        env:
          PATH: ${{ env.PATH }}:${{ env.USERPROFILE }}\.dotnet\tools
